In [17]:
import pandas as pd
import numpy as np

hare = pd.read_csv('55_Hare_Data_2012.txt')

![Hare Image](https://thumb.wikimedia.org/wikipedia/commons/thumb/8/8a/SNOWSHOE_HARE_%28Lepus_americanus%29_%285-28-2015%29_quoddy_head%2C_washington_co%2C_maine_-01_%2818988734889%29.jpg/1920px-SNOWSHOE_HARE_%28Lepus_americanus%29_%285-28-2015%29_quoddy_head%2C_washington_co%2C_maine_-01_%2818988734889%29.jpg?utm_source=commons.wikimedia.org&utm_campaign=index&utm_content=thumbnail&_=20170313021652)

In [ ]:
print(hare.dtypes)
print(hare.shape)
print(type(hare))

date           object
time           object
grid           object
trap           object
l_ear          object
r_ear          object
sex            object
age            object
weight        float64
hindft        float64
notes          object
b_key         float64
session_id      int64
study          object
dtype: object
(3380, 14)
<class 'pandas.core.frame.DataFrame'>
Series([], Name: count, dtype: int64)

In [11]:
hare.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3380 entries, 0 to 3379
Data columns (total 14 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        3380 non-null   object
 1   time        264 non-null    object
 2   grid        3380 non-null   object
 3   trap        3368 non-null   object
 4   l_ear       3332 non-null   object
 5   r_ear       3211 non-null   object
 6   sex         3028 non-null   object
 7   age         1269 non-null   object
 8   weight      2845 non-null   float64
 9   hindft      1633 non-null   float64
 10  notes       243 non-null    object
 11  b_key       3333 non-null   float64
 12  session_id  3380 non-null   int64
 13  study       3217 non-null   object
dtypes: float64(3), int64(1), object(10)
memory usage: 369.8+ KB

In [12]:
hare.describe()

            weight       hindft        b_key   session_id
count  2845.000000  1633.000000  3333.000000  3380.000000
mean   1346.081547   130.872627   500.640864    53.232249
std     345.160112    16.155295   299.421121    33.171355
min       0.000000    60.000000     1.000000     1.000000
25%    1180.000000   128.000000   235.000000    22.000000
50%    1400.000000   135.000000   464.000000    55.000000
75%    1580.000000   140.000000   755.000000    82.000000
max    2365.000000   160.000000  1034.000000   113.000000

| Values      | Definition          |
| ----------- | ------------------- |
| m           | male                |
| f           | female              |
| m?          | male, not confirmed |

In [5]:
hare['sex'].value_counts(dropna = False)

sex
F      1161
M       730
f       556
m       515
NaN     352
?        40
F?       10
f         4
m         4
f?        3
M?        2
m?        2
pf        1
Name: count, dtype: int64

In [ ]:
# Reassign sex values
hare = hare.replace(['M', 'm', 'M?', 'm?', 'm '], 'male')
hare = hare.replace(['F', 'f', 'F?', 'f?', 'pf', 'f '], 'female')
hare = hare.replace(['?', 'nan'], np.nan)

hare['sex'].value_counts(dropna = False)

sex
female    1735
male      1253
NaN        392
Name: count, dtype: int64

In [34]:
hare[['sex', 'weight']].groupby('sex').mean()

             weight
sex
female  1363.388560
male    1350.194643

In [52]:
# Streamlined Workflow

# Import packages
import pandas as pd
import numpy as np

# Read in data
hare = pd.read_csv('55_Hare_Data_2012.txt')

# Sex dict
sex_dict = {'M' : 'male', 'm' : 'male', 'm ' : 'male', 'M?' : 'male', 'm?' : 'male', 'F' : 'female', 'f' : 'female', 'f ' : 'female', 'F?' : 'female','f?' : 'female', 'pf' : 'female', '?' : np.nan, 'nan' : np.nan}

# Replace values
hare['simple_sex'] = hare['sex'].map(sex_dict)

# Counts of hares by sex
print('Hare count by sex:')
print(hare['simple_sex'].value_counts(dropna = False))

# Mean hare weight by sex
print('Mean hare weight by sex:')
print(hare[['simple_sex', 'weight']].groupby('simple_sex').mean())

Hare count by sex:
simple_sex
female    1735
male      1253
NaN        392
Name: count, dtype: int64
Mean hare weight by sex:
                 weight
simple_sex
female      1363.388560
male        1350.194643